"""nlp_schema_isolation

Revision ID: ceb5571c0d0c
Revises: 001
Create Date: 2026-02-20 12:33:22.241583

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ceb5571c0d0c'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nlp_queries_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_role', sa.String(length=50), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('routed_endpoint', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nlp_queries_log')),
    schema='nlp'
    )
    op.create_index(op.f('ix_nlp_nlp_queries_log_conversation_id'), 'nlp_queries_log', ['conversation_id'], unique=False, schema='nlp')
    op.create_index(op.f('ix_nlp_nlp_queries_log_created_at'), 'nlp_queries_log', ['created_at'], unique=False, schema='nlp')
    op.create_index(op.f('ix_nlp_nlp_queries_log_intent'), 'nlp_queries_log', ['intent'], unique=False, schema='nlp')
    op.create_table('nlp_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['nlp.nlp_queries_log.id'], name=op.f('fk_nlp_feedback_query_id_nlp_queries_log')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nlp_feedback')),
    schema='nlp'
    )
    op.create_index(op.f('ix_nlp_nlp_feedback_query_id'), 'nlp_feedback', ['query_id'], unique=False, schema='nlp')
    op.drop_table('staff')
    op.drop_table('situations')
    op.drop_table('alembic_version_nlp')
    op.drop_index(op.f('ix_customer_branch_movement_branch_id'), table_name='customer_branch_movement')
    op.drop_index(op.f('ix_customer_branch_movement_branch_id_enter_time'), table_name='customer_branch_movement')
    op.drop_index(op.f('ix_customer_branch_movement_enter_time'), table_name='customer_branch_movement')
    op.drop_index(op.f('ix_customer_branch_movement_exit_time'), table_name='customer_branch_movement')
    op.drop_table('customer_branch_movement')
    op.drop_index(op.f('ix_nlp_feedback_query_id'), table_name='nlp_feedback')
    op.drop_table('nlp_feedback')
    op.drop_table('recommendations')
    op.drop_table('alembic_version')
    op.drop_table('employees')
    op.drop_table('alembic_version', schema='core')
    op.drop_index(op.f('ix_nlp_queries_log_conversation_id'), table_name='nlp_queries_log')
    op.drop_index(op.f('ix_nlp_queries_log_created_at'), table_name='nlp_queries_log')
    op.drop_index(op.f('ix_nlp_queries_log_intent'), table_name='nlp_queries_log')
    op.drop_table('nlp_queries_log')
    op.drop_table('branches')
    op.drop_index(op.f('ix_branch_kpi_timeseries_branch_id'), table_name='branch_kpi_timeseries')
    op.drop_index(op.f('ix_branch_kpi_timeseries_branch_id_time_window'), table_name='branch_kpi_timeseries')
    op.drop_index(op.f('ix_branch_kpi_timeseries_time_window_start'), table_name='branch_kpi_timeseries')
    op.drop_table('branch_kpi_timeseries')
    op.drop_index(op.f('ix_events_start_time'), table_name='events')
    op.drop_index(op.f('ix_events_type'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_promotions_branch_id'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_start_date'), table_name='promotions')
    op.drop_table('promotions')
    op.drop_index(op.f('ix_tasks_branch_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_employee_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_time'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('customers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('customer_id', name=op.f('pk_customers'))
    )
    op.create_table('tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('branch_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recommendation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_tasks_branch_id_branches')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_tasks_employee_id_employees')),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], name=op.f('fk_tasks_recommendation_id_recommendations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_time'), 'tasks', ['time'], unique=False)
    op.create_index(op.f('ix_tasks_employee_id'), 'tasks', ['employee_id'], unique=False)
    op.create_index(op.f('ix_tasks_branch_id'), 'tasks', ['branch_id'], unique=False)
    op.create_table('promotions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('item_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('promotion_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('discount_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_promotions_branch_id_branches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotions'))
    )
    op.create_index(op.f('ix_promotions_start_date'), 'promotions', ['start_date'], unique=False)
    op.create_index(op.f('ix_promotions_branch_id'), 'promotions', ['branch_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('repetition', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('global_event', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_type'), 'events', ['type'], unique=False)
    op.create_index(op.f('ix_events_start_time'), 'events', ['start_time'], unique=False)
    op.create_table('branch_kpi_timeseries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('time_window_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('time_window_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('traffic_index', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('conversion_proxy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('congestion_level', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('growth_momentum', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('utilization_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('staffing_adequacy_index', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bottleneck_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_branch_kpi_timeseries_branch_id_branches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branch_kpi_timeseries'))
    )
    op.create_index(op.f('ix_branch_kpi_timeseries_time_window_start'), 'branch_kpi_timeseries', ['time_window_start'], unique=False)
    op.create_index(op.f('ix_branch_kpi_timeseries_branch_id_time_window'), 'branch_kpi_timeseries', ['branch_id', 'time_window_start'], unique=False)
    op.create_index(op.f('ix_branch_kpi_timeseries_branch_id'), 'branch_kpi_timeseries', ['branch_id'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('peak_time', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('neighbors', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('restocking_schedule', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches'))
    )
    op.create_table('nlp_queries_log',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('query_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('intent', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('routed_endpoint', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nlp_queries_log'))
    )
    op.create_index(op.f('ix_nlp_queries_log_intent'), 'nlp_queries_log', ['intent'], unique=False)
    op.create_index(op.f('ix_nlp_queries_log_created_at'), 'nlp_queries_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_nlp_queries_log_conversation_id'), 'nlp_queries_log', ['conversation_id'], unique=False)
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc')),
    schema='core'
    )
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees'))
    )
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.create_table('recommendations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('situation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('expected_impact', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('value_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['situation_id'], ['situations.id'], name=op.f('fk_recommendations_situation_id_situations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    op.create_table('nlp_feedback',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('query_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['nlp_queries_log.id'], name=op.f('fk_nlp_feedback_query_id_nlp_queries_log'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nlp_feedback'))
    )
    op.create_index(op.f('ix_nlp_feedback_query_id'), 'nlp_feedback', ['query_id'], unique=False)
    op.create_table('customer_branch_movement',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('branch_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('enter_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('exit_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('action_type', postgresql.ENUM('PASSED', 'ENTERED', name='actiontype'), autoincrement=False, nullable=False),
    sa.Column('event_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_customer_branch_movement_branch_id_branches')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_customer_branch_movement_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_branch_movement')),
    sa.UniqueConstraint('event_hash', name=op.f('uq_customer_branch_movement_event_hash'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_customer_branch_movement_exit_time'), 'customer_branch_movement', ['exit_time'], unique=False)
    op.create_index(op.f('ix_customer_branch_movement_enter_time'), 'customer_branch_movement', ['enter_time'], unique=False)
    op.create_index(op.f('ix_customer_branch_movement_branch_id_enter_time'), 'customer_branch_movement', ['branch_id', 'enter_time'], unique=False)
    op.create_index(op.f('ix_customer_branch_movement_branch_id'), 'customer_branch_movement', ['branch_id'], unique=False)
    op.create_table('alembic_version_nlp',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_nlp_pkc'))
    )
    op.create_table('situations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('situation_label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('severity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_situations_branch_id_branches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_situations'))
    )
    op.create_table('staff',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('shift_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('shift_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_staff_branch_id_branches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff'))
    )
    op.drop_index(op.f('ix_nlp_nlp_feedback_query_id'), table_name='nlp_feedback', schema='nlp')
    op.drop_table('nlp_feedback', schema='nlp')
    op.drop_index(op.f('ix_nlp_nlp_queries_log_intent'), table_name='nlp_queries_log', schema='nlp')
    op.drop_index(op.f('ix_nlp_nlp_queries_log_created_at'), table_name='nlp_queries_log', schema='nlp')
    op.drop_index(op.f('ix_nlp_nlp_queries_log_conversation_id'), table_name='nlp_queries_log', schema='nlp')
    op.drop_table('nlp_queries_log', schema='nlp')
    # ### end Alembic commands ###
